### ISSUE TITLE
Suggestion: Commands + Config enable/disable

### ISSUE THREAD

**Issue by TetroYT** [thebigsmileXD/WarpUI#11]
add a command to open the warpui menu

also add an option to enable and disabled compass and clock

**Comment by inxomnyaa** [comment]
> add a command to open the warpui menu

`/warpui` ok

> also add an option to enable and disabled compass and clock

Good idea

**Comment by TetroYT** [comment]
thanks :D

**Comment by pistolswang013** [comment]
I set the item give to false and it still continued to give me the item but just gave me a internal server error when pressing it

**Comment by inxomnyaa** [comment]
The feature has not be implemented yet

**Comment by inxomnyaa** [comment]
I am currently implementing this, since https://github.com/thebigsmileXD/WarpUI/pull/12#issuecomment-542139932 #12 did not have all features.

**Comment by inxomnyaa** [comment]
Implemented
