### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TetroYT** [thebigsmileXD/WarpUI#13]
is it possible for me to disable the clock and compass?

**Comment by inxomnyaa** [comment]
It is coming in #12

**Comment by inxomnyaa** [comment]
See https://github.com/thebigsmileXD/WarpUI/blob/3c8af24998fded36d29d3f4f4e5e02cb6ce7510a/resources/config.yml

**Comment by inxomnyaa** [comment]
Implemented
