### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/WarpUI#14]
use xenialdan\customui\elements\Button;
use xenialdan\customui\windows\SimpleForm;

My console says: 
Server thread/CRITICAL Error: "Class 'xenialdan\customui\windows\SimpleForm' not found" (EXCEPTION) in "plugins/WarpUI-3c8af24998fded36d29d3f4f4e5e02cb6ce7510a/src/xenialdan/WarpUI/Loader" at line 99

**Comment by inxomnyaa** [comment]
Grab the phar on poggit. https://poggit.pmmp.io/ci/thebigsmileXD/WarpUI/~
