### ISSUE TITLE
Nothing in the config file 

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/WarpUI#15]
The phar thing you have me had no content in the config file

**Comment by inxomnyaa** [comment]
Just merged the branch new_features into master. I am not sure if the new features work, but the resources folder is now there

**Comment by ghost** [comment]
wdym and also how do i add warps seems its not loading my previous warps and the master doesnt work it keeps crashing if i use it

**Comment by inxomnyaa** [comment]
> wdym 

Update and you will have a config.

**Comment by inxomnyaa** [comment]
Please check #16, i noticed that i was not working on this project, but another.

**Comment by inxomnyaa** [comment]
Implemented
