### ISSUE TITLE
Permission doesn't works

### ISSUE THREAD

**Issue by creeperplayer20** [thebigsmileXD/WarpUI#18]
Hi, when i click with the compass it shows 0 warps, I did 2 warps called "Spawn" "Enchant". I did the warp "Spawn" in the "World" , so when I added the permission to the players it doesn't works (warps) permissions that I give: warpui.World.Spawn / warpui.world.spawn / warpui.World.spawn / warpui.world.Spawn

**Comment by creeperplayer20** [comment]
You saw nothing 👀

**Comment by inxomnyaa** [comment]
:P I think it is warpui.worlds
If you need further help with the plugin or have suggestions, let me know :+1:
