### ISSUE TITLE
Compass not working

### ISSUE THREAD

**Issue by ghost** [thebigsmileXD/WarpUI#2]
Compass isnt working when being clicked with

**Comment by inxomnyaa** [comment]
Are you sure you have forms (see #1 )?
I need more information:

Device type
game version
pocketmine version/last commit/build

if on phone: try long-hold into the air

**Comment by ghost** [comment]
Linux Ubuntu
MC 1.2 Bedrock 
PocketMine-MP version 1.7dev-344 "[REDACTED]" (API 3.0.0-ALPHA9)

Plugin installed, when clicking with the compass nothing happens.

**Comment by inxomnyaa** [comment]
Since when is there a linux version of the game?

**Comment by ghost** [comment]
@thebigsmileXD you asked for device type, Included the version which is again, 1.2.3, be more specific about the device. I use Windows 10

**Comment by inxomnyaa** [comment]
Are you sure you are using the compass that the plugin gives you and using the forms-api branch of pmmp/PocketMine-MP or ClearSky/PocketMine-MP?

**Comment by ghost** [comment]
@thebigsmileXD pmmp, and yes, I'm using the compass, its labeled warp.

**Comment by inxomnyaa** [comment]
Again: Correct branch?

**Comment by ghost** [comment]
@thebigsmileXD yes man
