### ISSUE TITLE
Bug/help?

### ISSUE THREAD

**Issue by TetroYT** [thebigsmileXD/WarpUI#20]
Non ops cant use the warp command i added both perm nodes and they still cant open the menu i added warpui.warp.(warp name), warpui.warp and warpui.warp.* and still says i dont have permission
![1F9193B1-B54B-49A9-B121-BD3302A6A62A](https://user-images.githubusercontent.com/49662383/73731515-8561c180-4730-11ea-888a-8fd810985e50.jpeg)

**Comment by inxomnyaa** [comment]
Do they see the warps in the UI?

**Comment by inxomnyaa** [comment]
Also, for warpui.warp.warpname, try without color codes and lowercase i.e. warpui.warp.crates

**Comment by TetroYT** [comment]
No they can’t open the UI

**Comment by inxomnyaa** [comment]
They should be able to _open_ the ui regardless of permissions. I just uploaded a patch to fix `.*` permissions
So warpui.warp, warpui.world, warpui.warp.* and warpui.world.* should now work

**Comment by inxomnyaa** [comment]
I changed some permission logic issues and upgraded the README. Please check if version 3.3.0 suits your needs and properly works. 
If there are further problems, please leave a comment and i will reopen the issue.
