### ISSUE TITLE
[Unconfirmed] Permission problems

### ISSUE THREAD

**Issue by creeperplayer20** [thebigsmileXD/WarpUI#21]
I found bug, where players can remove or add warps with no op

**Comment by inxomnyaa** [comment]
Do they have the `warpui.command.warp.add` permission?
Does your permission managing plugin work properly?
The permissions are defaulting to `op` perm in plugin.yml, only `warpui.command` has "true" as default, which is needed, without they could not use the item or command /warpui warp at all.
If you use PurePerms, try adding the permission with a `-` in front, so
`-warpui.command.warp.add`
Also take note that the permissions have been renamed for consistency in 3.3.1!

**Comment by creeperplayer20** [comment]
hi i only gave to them this permissions:

  - warpui.warp.spawn
  - warpui.warp.enchant

btw they have access to the other warps without perms....

**Comment by inxomnyaa** [comment]
I need someone to confirm this

**Comment by RodrigoSKBR** [comment]
I have this problem too
