### ISSUE TITLE
Worldui issue

### ISSUE THREAD

**Issue by Fairydrip** [thebigsmileXD/WarpUI#22]
Recently, when joining into my server I've experienced a bug that made me and all the members join into the other world, with the clock i can easily get back to the other world but I want it so the main world is the spawn world and I can't seem to get it that way, is there a certain way we can set the spawn world? I don't want my new members spawning in the other one. Help!!

**Comment by inxomnyaa** [comment]
This plugin does not modify the player data nor the default world / world spawn. It only works as a utility for teleporting between those.
