### ISSUE TITLE
i have a trouble with teleporting, (warpui teleport {warp} ), Internal server error... How can i fix it??? Im using 1.16.0.2 ver

### ISSUE THREAD

**Issue by skipppdev** [thebigsmileXD/WarpUI#24]
![image](https://user-images.githubusercontent.com/67657789/88775110-eef3e300-d149-11ea-9387-0485625ad128.png)

**Comment by inxomnyaa** [comment]
![image](https://cdn.discordapp.com/attachments/287339519500353537/738085032773812304/download.jpeg)
We just reached a new level:
**Uploading a screenshot of Internal Server Error**
