### ISSUE TITLE
all /warpui commands available to non-ops.

### ISSUE THREAD

**Issue by CrafterLTU** [thebigsmileXD/WarpUI#25]
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/50147743/89404655-053e0800-d723-11ea-9440-01f90b2e128f.gif)
![eadsd](https://user-images.githubusercontent.com/50147743/89404753-2a327b00-d723-11ea-834c-b42c24265048.PNG)

Here i have a gif and the picture of the rank and perms i was using, i was not op, i tried to prove it by doing /gamemode but again, i was not op, i had no permissions regarding the plugin and i could still use it and i could add and remove warps without any permissions.

**Comment by inxomnyaa** [comment]
add negative perm im pp
