### ISSUE TITLE
Broke on alpha 11

### ISSUE THREAD

**Issue by artulloss** [thebigsmileXD/WarpUI#7]
13.02 21:05:07 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::sendForm()" (EXCEPTION) in "WarpUI-master/src/xenialdan/WarpUI/EventListener" at line 35
13.02 21:05:07 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/MethodEventExecutor(38): xenialdan\WarpUI\EventListener->onInteract(pocketmine\event\player\PlayerInteractEvent object)
13.02 21:05:07 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(xenialdan\WarpUI\EventListener object, pocketmine\event\player\PlayerInteractEvent object)
13.02 21:05:07 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginManager(683): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerInteractEvent object)
13.02 21:05:07 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2361): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerInteractEvent object)
13.02 21:05:07 [Server] Server thread/DEBUG #4

**Comment by inxomnyaa** [comment]
forms-api still runs ALPHA10 https://github.com/pmmp/PocketMine-MP/blob/forms-api/src/pocketmine/PocketMine.php#L84

see https://github.com/thebigsmileXD/MagicWE2/wiki/Command:---brush#troubleshooting for fixes
