### ISSUE TITLE
Suggestion: Warp perms

### ISSUE THREAD

**Issue by mikeygio10** [thebigsmileXD/WarpUI#8]
You should add a way to set a perm per warp so like I can’t tp to warp shop I can only to if I have a certain perm but the perm is only for that warp

**Comment by provsnoobgaming** [comment]
you gotta chill out with those issues
make a fork and do it yourself
and make a PR
this kid coming from some free monehub.de/what ever free host need to be stopped

**Comment by inxomnyaa** [comment]
Will be added in #12

**Comment by inxomnyaa** [comment]
Since this did not happen in #12, will add it asap in a commit

**Comment by inxomnyaa** [comment]
Implemented.
`warpui.warp.` + the lowercase warp name
`warpui.world.` + the lowercase world name
